#!/bin/bash

### BEGIN INIT INFO
# Provides:          maker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts maker
# Description:       starts maker
### END INIT INFO

# /etc/init.d/maker

start() {
    echo -n "Starting maker: "
    echo "--------------------------------------------------" >> /var/log/maker
    date +"! %Y/%m/%d %a %T : Launching ros on docker" >> /var/log/maker

    cd /home/pi/Documents/maker
    export DISPLAY=:0
    ./reflow_oven.py &

    date +"! %Y/%m/%d %a %T : Finished launching ros on docker." >> /var/log/maker
    echo "--------------------------------------------------" >> /var/log/maker
    echo "Done"

    touch /var/lock/subsys/maker
}

stop() {
    echo -n "Shutting down maker: "
    echo "--------------------------------------------------" >> /var/log/maker
    date +"! %Y/%m/%d %a %T : Shutting Down maker." >>/var/log/maker
    echo "maker"

    killall -9 reflow_oven.py

    echo "Done."
    date +"! %Y/%m/%d %a %T : Finished." >> /var/log/maker
    echo "--------------------------------------------------" >> /var/log/maker

    rm -f /var/lock/subsys/maker
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Usage: nturt_ros { start | stop | restart }"
        exit 1
    ;;
esac
exit 0
